# Generated by Django 6.0.2 on 2026-02-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=50)),
                ('delivery_type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='delivery', max_length=20)),
                ('shipping_option', models.CharField(blank=True, max_length=50)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_suburb', models.CharField(blank=True, max_length=100)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_province', models.CharField(blank=True, max_length=100)),
                ('address_postal_code', models.CharField(blank=True, max_length=10)),
                ('payment_method', models.CharField(choices=[('eft', 'EFT/Bank Transfer'), ('cash', 'Cash on Delivery'), ('stripe', 'Credit Card')], default='eft', max_length=20)),
                ('items_json', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('flower', 'Flowers'), ('edibles', 'Edibles'), ('concentrates', 'Concentrates'), ('accessories', 'Accessories')], default='flower', max_length=20)),
                ('strain', models.CharField(choices=[('sativa', 'Sativa'), ('indica', 'Indica'), ('hybrid', 'Hybrid'), ('all', 'All')], default='hybrid', max_length=20)),
                ('thc', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icon', models.CharField(choices=[('🌿', '🌿 Leaf'), ('🍁', '🍁 Maple'), ('🌸', '🌸 Flower'), ('🍀', '🍀 Clover'), ('🎋', '🎋 Bamboo'), ('🌺', '🌺 Hibiscus'), ('🍄', '🍄 Mushroom'), ('🌵', '🌵 Cactus'), ('🎄', '🎄 Christmas Tree'), ('🌲', '🌲 Evergreen'), ('🍃', '🍃 Herb'), ('☘️', '☘️ Shamrock'), ('🌱', '🌱 Seedling'), ('🌿', '🌿 Herb'), ('🍪', '🍪 Cookie'), ('🍬', '🍬 Candy'), ('🍫', '🍫 Chocolate'), ('🍩', '🍩 Donut'), ('🍦', '🍦 Ice Cream'), ('🧁', '🧁 Cupcake'), ('🍮', '🍮 Pudding'), ('🍭', '🍭 Lollipop'), ('💧', '💧 Drop'), ('🧪', '🧪 Test Tube'), ('💎', '💎 Diamond'), ('🔮', '🔮 Crystal Ball'), ('⚗️', '⚗️ Alembic'), ('🧴', '🧴 Lotion'), ('💊', '💊 Pill'), ('🏺', '🏺 Amphora'), ('🫙', '🫙 Jar'), ('📦', '📦 Box'), ('🛍️', '🛍️ Shopping Bag'), ('⚙️', '⚙️ Gear'), ('🔧', '🔧 Wrench'), ('🛠️', '🛠️ Tools'), ('🔥', '🔥 Fire'), ('💨', '💨 Smoke'), ('⚡', '⚡ Bolt'), ('🔋', '🔋 Battery')], default='🌿', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='QueueBlaze', max_length=200)),
                ('site_description', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('operating_hours', models.CharField(blank=True, max_length=200)),
                ('about_title', models.CharField(blank=True, max_length=200)),
                ('about_content', models.TextField(blank=True)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
