# Generated by Django 6.0.2 on 2026-02-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitesettings_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
